service: otrace-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  region: us-west-2
  stage: sandbox
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:Query"
      Resource:
        - "Fn::GetAtt": [ tracingTable, Arn ]

plugins:
  - serverless-go-plugin

custom:
  go:
    supportedRuntimes: [ "provided.al2" ]
    buildProvidedRuntimeAsBootstrap: true

package:
  patterns:
    - '!./**'
  individually: true

functions:
  create_consent:
    handler: handlers/create_consent/main.go
    events:
      - http:
          path: /create-consent
          method: POST
  change_consent:
    handler: handlers/change_consent/main.go
    events:
      - http:
          path: /change-consent
          method: POST
  delete_consent:
    handler: handlers/delete_consent/main.go
    events:
      - http:
          path: /delete-consent
          method: POST
  share_data:
    handler: handlers/share_data/main.go
    events:
      - http:
          path: /share-data
          method: POST
  use_data:
    handler: handlers/use_data/main.go
    events:
      - http:
          path: /use-data
          method: POST
  user_dashboard:
    handler: handlers/user_dashboard/main.go
    events:
      - http:
          path: /user-dashboard
          method: POST
  notify_violation:
    handler: handlers/notify_violation/main.go
    events:
      - http:
          path: /notify-violation
          method: POST

resources:
  Resources:
    tracingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tracingTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: trace_id
            AttributeType: S
          - AttributeName: data_subject
            AttributeType: S
        KeySchema:
          - AttributeName: trace_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: DataSubjectIndex
            KeySchema:
              - AttributeName: data_subject
                KeyType: HASH
            Projection:
              ProjectionType: ALL
